# exclude-categories: "exclude categories by providing its name"
# exclude-paths: "exclude paths or files from scan"
# exclude-queries: "exclude queries by providing the query ID"
# exclude-results: "exclude results by providing a list of similarity IDs of a result"
# exclude-severities: "low,info"
include-queries: "e7a9b9d1-1b7d-4b8b-8b5b-2a1c5b5b5b5b"
fail-on: "high,medium"
# libraries-path: "path to directory with libraries (default "./assets/libraries")"
# log-file: true
log-level: "INFO"
# log-path: path to the log file
minimal-ui: false
no-color: false
no-progress: true
# output-name: "name used on report creations (default \"results\")"
# output-path: "directory path to store reports"
path: "./"
# payload-path: "file path to store source internal representation in JSON format"
# preview-lines: 3
# profiling: "enables performance profiler that prints resource consumption metrics in the logs during the execution (CPU, MEM)"
# queries-path: "path to directory with queries (default ./assets/queries) (default './assets/queries')"
# report-formats: "formats in which the results will be exported (all, asff, codeclimate, csv, cyclonedx, glsast, html, json, junit, pdf, sarif, sonarqube) (default [json])"
silent: false
# type: "type of queries to use in the scan"
# timeout: "number of seconds the query has to execute before being canceled"
verbose: true
# disable-full-descriptions: "disable request for full descriptions and use default vulnerability descriptions"
