scan:
  queries:
    include:
      - "e7a9b9d1-1b7d-4b8b-8b5b-2a1c5b5b5b5b" # Example query ID for secrets detection
  paths:
    - "./" # Scan the entire repository
  exclude_paths:
    - "node_modules"
    - "dist"
    - ".git"
