name: KICS Scan

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  kics-scan:
    name: Run KICS Scan
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Run KICS Scan
      - name: Run KICS with Configuration
        uses: checkmarx/kics-github-action@v2.1.15
        with:
          scan-path: .
          config-path: ./kics-config.yaml
          output-name: kics-results.json
          output-format: json
