# This is a basic workflow to help you get started with Actions

name: trivy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  RunTerraformValidation:
    name: Run Terraform SAST
    runs-on: ubuntu-latest

    steps:
      - name: Clone the Repository
        uses: actions/checkout@v4

      # Results have to be a table as the organisation does not have Advanced Security license.
      - name: Terraform Trivy Scan
        uses: aquasecurity/trivy-action@0.19.0
        with:
          scan-type: 'config'
          exit-code: '1'
